### ISSUE TITLE
5. Programación Asíncrona y Eventos

### ISSUE THREAD

**Issue by mr-pineda** [FernandaAvello/ABPro#4]
- Integra **programación asíncrona** utilizando **async/await** y **promesas** para la simulación de un registro de citas.
- Implementa **event listeners** para capturar eventos del usuario, como la confirmación de una cita o la solicitud de información de un doctor.

RÚBRICA: Se implementan correctamente operaciones asíncronas utilizando **async/await** y **promesas**, y se manejan eventos mediante **listeners** para capturar las acciones del usuario.

**Comment by mr-pineda** [comment]
@FernandaAvello quiero tomar este desarrollo, pero como tú que estás viendo lo de guardar las citas en JSON. ¿Crees que el primer punto pueda estar relacionado con lo que estás implementando? O lo puedo trabajar yo con otra fuente de citas

**Comment by FernandaAvello** [comment]
A no lo habia leido bien, el primer punto si creo que lo voy a a hacer, lo
del async await. El otro podrias hacerlo quizas en vez de con citas, con la
otra sugerencia que es con informacion del doctor?

**Comment by mr-pineda** [comment]
Como ya esta implementado se cierra el issue
